//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroHorasPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroHoras
    {
        public int IdControlHora { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> HorasTotales { get; set; }
        public Nullable<int> IdCatEmpresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
